name: Tests
on: 
  push:
    branches:
      - main
      
jobs:
  tests:
    name: Unit Testing
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
              cd "Discrete mathematics"
              cd Discra
              dotnet test
